# System, profile, and shortcut commands for help

function Show-HelpUsageSystem {
    Write-HelpUsageEntry ".\run.ps1 os <action>" "OS housekeeping: clean, temp-clean, hib-off, flp, add-user ('os -h' for full list)"
    Write-HelpUsageEntry ".\run.ps1 os power [flags]" "Set display/sleep/disk/hibernate timeouts (--display N --sleep N --disk N --hibernate N | --never | --ac-only | --dc-only | --dry-run)"
    Write-HelpUsageEntry ".\run.ps1 os hib-off | hib-on" "Disable / enable Windows hibernation"
    Write-HelpUsageEntry ".\run.ps1 os browser <name>" "Set default web browser (chrome | firefox | edge | brave | opera | vivaldi | librewolf)"
    Write-HelpUsageEntry ".\run.ps1 os email <name>" "Set default mail client (outlook | thunderbird | mailbird | em-client | windows-mail)"
    Write-HelpUsageEntry ".\run.ps1 os clean | temp-clean" "Disk cleanup (categories, buckets, consent system) or just temp dirs"
    Write-HelpUsageEntry ".\run.ps1 os dev-cleanup [-y]" "Clean dev tools caches (Go, pnpm, npm, choco, yarn, bun, pip, cargo, nuget)"
    Write-HelpUsageEntry ".\run.ps1 clean-dev [-y]" "Top-level shortcut for 'os dev-cleanup' (supports --dry-run, --yes)"
    Write-HelpUsageEntry ".\run.ps1 dev-clean [-y]" "Alias for 'clean-dev' (supports --dry-run, --yes)"
    Write-HelpUsageEntry ".\run.ps1 agy <action>" "Antigravity maintenance: clear | clean | predict | undo | list-backups ('agy help')"
    Write-HelpUsageEntry ".\run.ps1 agy clear --keep 10" "Prune conversations keeping latest 10 intact (safe predict mode by default)"
    Write-HelpUsageEntry ".\run.ps1 agy clear --keep 10 -y" "Apply conversation prune & cache scrub (keeps latest 10 intact)"
    Write-HelpUsageEntry ".\run.ps1 agy undo latest" "Rollback the most recent conversation pruning transaction"
    Write-HelpUsageEntry ".\run.ps1 clean-agy 10" "Top-level shortcut for 'agy clear --keep 10' (supports -y, --dry-run)"
    Write-HelpUsageEntry ".\run.ps1 os add-user | edit-user | remove-user" "Local Windows user management (add/edit/remove, JSON-bulk variants too)"
    Write-HelpUsageEntry ".\run.ps1 ssh <verb>" "SSH keys: gen | view | read | cat | search | install | revoke | ledger ('ssh help')"
    Write-HelpUsageEntry ".\run.ps1 ssh view" "Pretty-print ~/.ssh (public keys + masked private + ledger summary)"
    Write-HelpUsageEntry ".\run.ps1 ssh search <p>" "Substring/regex search across ~/.ssh files AND the cross-OS ledger"
    Write-HelpUsageEntry ".\run.ps1 menu <verb> [target]" "Context-menu manager: install|uninstall|list|help; targets all|pwsh|wt|conemu|vscode|sf"
    Write-HelpUsageEntry ".\run.ps1 menu install all -y" "Install every right-click menu (PowerShell, Windows Terminal, ConEmu, VS Code, SF)"
    Write-HelpUsageEntry ".\run.ps1 menu install pwsh|wt|conemu" "Install one menu only (PowerShell / Windows Terminal / ConEmu submenu)"
    Write-HelpUsageEntry ".\run.ps1 menu uninstall conemu" "Snapshot to .reg + remove a target's right-click entries"
    Write-HelpUsageEntry ".\run.ps1 vscode-folder <action>" "VS Code folder-only context-menu repair ('vscode-folder help')"
    Write-HelpUsageEntry ".\run.ps1 vscode-context-menu install" "Legacy alias for 'menu install vscode' (kept for back-compat)"
    Write-HelpUsageEntry ".\run.ps1 profile <name>" "Run a profile recipe (see 'Profiles' section below for list)"
    Write-HelpUsageEntry ".\run.ps1 profile tree <name>" "View the full installation tree of a profile"
    Write-HelpUsageEntry ".\run.ps1 install <profile>" "Same as above -- 'install minimal' == 'profile minimal'"
    Write-HelpUsageEntry ".\run.ps1 profile list" "Show all available profiles with descriptions"
    Write-HelpUsageEntry ".\run.ps1 gsa" "git safe.directory='*' (wildcard, idempotent)"
    Write-HelpUsageEntry ".\run.ps1 gsa --scan <path>" "Add each .git repo under <path> individually"
    Write-HelpUsageEntry ".\run.ps1 git-tools <action>" "Git config helpers ('git-tools help' for actions)"
    Write-HelpUsageEntry ".\run.ps1 path <dir>" "Set default dev directory"
    Write-HelpUsageEntry ".\run.ps1 path" "Show current dev directory"
    Write-HelpUsageEntry ".\run.ps1 path --reset" "Clear saved path, use smart detection"
    Write-HelpUsageEntry ".\run.ps1 -I <number>" "Run a specific script by ID"
    Write-HelpUsageEntry ".\run.ps1 -d" "Shortcut for -I 12 (interactive menu)"
    Write-HelpUsageEntry ".\run.ps1 -a" "Shortcut for -I 13 (audit mode)"
    Write-HelpUsageEntry ".\run.ps1 -h" "Shortcut for -I 13 -Report (health check)"
    Write-HelpUsageEntry ".\run.ps1 -v" "Shortcut for -I 1  (install VS Code)"
    Write-HelpUsageEntry ".\run.ps1 -w" "Shortcut for -I 14 (install Winget)"
    Write-HelpUsageEntry ".\run.ps1 -t" "Shortcut for -I 15 (Windows tweaks)"
    Write-HelpUsageEntry ".\run.ps1 -Defaults" "Use all defaults, prompt to confirm"
    Write-HelpUsageEntry ".\run.ps1 -Defaults -Y" "Use all defaults, skip confirmation"
    Write-HelpUsageEntry ".\run.ps1 -I <number> -Merge" "Run with merge flag (script 02)"
    Write-HelpUsageEntry ".\run.ps1 -I <number> -Clean" "Wipe cache, then run"
    Write-HelpUsageEntry ".\run.ps1 -CleanOnly" "Wipe all cached data"
    Write-HelpUsageEntry ".\run.ps1 -Help" "Show this help"
    Write-HelpUsageEntry ".\run.ps1 -List" "Show keyword table only"
}
